package org.cxsbs.core;

public enum Sound {
    JUMP, LAND, RIFLE, PUNCH1, SG, CG,
    RLFIRE, RLHIT, WEAPLOAD, ITEMAMMO, ITEMHEALTH,
    ITEMARMOUR, ITEMPUP, ITEMSPAWN, TELEPORT, NOAMMO, PUPOUT,
    PAIN1, PAIN2, PAIN3, PAIN4, PAIN5, PAIN6,
    DIE1, DIE2,
    FLAUNCH, FEXPLODE,
    SPLASH1, SPLASH2,
    GRUNT1, GRUNT2, RUMBLE,
    PAINO,
    PAINR, DEATHR,
    PAINE, DEATHE,
    PAINS, DEATHS,
    PAINB, DEATHB,
    PAINP, PIGGR2,
    PAINH, DEATHH,
    PAIND, DEATHD,
    PIGR1, ICEBALL, SLIMEBALL,
    JUMPPAD, PISTOL,

    V_BASECAP, V_BASELOST,
    V_FIGHT,
    V_BOOST, V_BOOST10,
    V_QUAD, V_QUAD10,
    V_RESPAWNPOINT,

    FLAGPICKUP,
    FLAGDROP,
    FLAGRETURN,
    FLAGSCORE,
    FLAGRESET,

    BURN,
    CHAINSAW_ATTACK,
    CHAINSAW_IDLE,

    HIT,
    NONE;
}
