package enetwrapper;
import java.nio.ByteBuffer;

import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ew_Event extends Structure<ew_Event, ew_Event.ByValue, ew_Event.ByReference > {
	public int clientid;
	public int type;
	public int channel;
	/// C type : unsigned char*
	public Pointer data;
	public int datalen;
	public ew_Event() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"clientid", "type", "channel", "data", "datalen"});
	}
	/// @param data C type : unsigned char*
	public ew_Event(int clientid, int type, int channel, Pointer data, int datalen) {
		super();
		this.clientid = clientid;
		this.type = type;
		this.channel = channel;
		this.data = data;
		this.datalen = datalen;
		initFieldOrder();
	}
	
	public ByteBuffer getDataBuffer() {
		return this.data.getByteBuffer(0, this.datalen);
	}
	
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected ew_Event newInstance() { return new ew_Event(); }
	public static ew_Event[] newArray(int arrayLength) {
		return Structure.newArray(ew_Event.class, arrayLength);
	}
	public static class ByReference extends ew_Event implements Structure.ByReference {};
	public static class ByValue extends ew_Event implements Structure.ByValue {};
}
